### ISSUE TITLE
ES 7.8.1版本创建indexPattern报错

### ISSUE THREAD

**Issue by linger000** [TongchengOpenSource/ckibana#36]
CKibana version: v1.0.2
ES version:7.8.1
Operating system version: CentOS 7

报错如下：
com.alibaba.fastjson2.JSONException: parseLong error, value : {"value":0,"relation":"eq"}
	at com.alibaba.fastjson2.JSONReader.toLong(JSONReader.java:2543)
	at com.alibaba.fastjson2.JSONReader.getInt64Value(JSONReader.java:608)
	at com.alibaba.fastjson2.JSONReaderUTF8.readInt64Value(JSONReaderUTF8.java:2125)
	at com.alibaba.fastjson2.reader.ORG_3_3_Hits.readObject(Unknown Source)
	at com.alibaba.fastjson2.reader.ORG_1_9_Response.readObject(Unknown Source)
	at com.alibaba.fastjson2.JSON.parseObject(JSON.java:642)
	at com.alibaba.fastjson2.JSONObject.parseObject(JSONObject.java:1942)
	at com.ly.ckibana.handlers.SearchHandler.doHandle(SearchHandler.java:88)
	at com.ly.ckibana.handlers.BaseHandler.handle(BaseHandler.java:76)
	at com.ly.ckibana.configure.web.adpter.BaseHandlerAdapter.handle(BaseHandlerAdapter.java:39)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

**Comment by qzhello** [comment]
已解决781版本的问题。见#37
