### ISSUE TITLE
kibana 页面静置一段时间后报Error loading data

### ISSUE THREAD

**Issue by jiaozi07** [TongchengOpenSource/ckibana#62]
必须要强制刷新，单独点刷新时间报下列错误
![image](https://github.com/user-attachments/assets/398cb409-308e-4d19-8084-2ec7001a118f)

**Comment by jiaozi07** [comment]
```
2024-12-31 14:09:12.393 ERROR [common-pool-0  ] [com.ly.ckibana.service.EsClientUtil     ] [] bulk error
java.io.IOException: Connection reset
        at org.elasticsearch.client.RestClient.extractAndWrapCause(RestClient.java:935)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:300)
        at org.elasticsearch.client.RestClient.performRequest(RestClient.java:288)
        at com.ly.ckibana.service.EsClientUtil.performRequest(EsClientUtil.java:103)
        at com.ly.ckibana.service.EsClientUtil.doRequest(EsClientUtil.java:80)
        at com.ly.ckibana.service.EsClientUtil.doRequest(EsClientUtil.java:91)
        at com.ly.ckibana.service.EsClientUtil.bulk(EsClientUtil.java:160)
        at com.ly.ckibana.service.EsClientUtil.saveBatch(EsClientUtil.java:341)
        at com.ly.ckibana.service.SqlMonitorService.batchRecord(SqlMonitorService.java:88)
        at com.ly.ckibana.service.SqlMonitorService.asyncRecordMonitoring(SqlMonitorService.java:120)
        at com.ly.ckibana.configure.thread.ThreadPoolConfigurer.lambda$init$1(ThreadPoolConfigurer.java:94)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.SocketException: Connection reset
        at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:394)
        at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:426)
        at org.apache.http.impl.nio.reactor.SessionInputBufferImpl.fill(SessionInputBufferImpl.java:231)
        at org.apache.http.impl.nio.codecs.AbstractMessageParser.fillBuffer(AbstractMessageParser.java:136)
        at org.apache.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:241)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:81)
        at org.apache.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:39)
        at org.apache.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        ... 1 common frames omitted
```

**Comment by tclxjww0328** [comment]
@qzhello
